version: '2'
services:
    recipeapp-app:
        image: recipeapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://recipeapp-mysql:3306/recipeapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    recipeapp-mysql:
        extends:
            file: mysql.yml
            service: recipeapp-mysql
